---
config:
  theme: redux-color
  look: neo
---
  sequenceDiagram
    autonumber
    participant Client
    participant Filter as AuthInterceptor
    participant AuthService as AuthService
    participant DB as Database
    participant Controller as GitController
    participant Service as GitService
    participant Library as JGit

  Client->>Filter: POST /api/repos/{owner}/{name}/clone <br> (with CSRF and Session Token)
    Note over Filter: Extract Tokens <br> From Header

    Filter->>AuthService: authenticate(sessionToken, <br> csrfToken)
    AuthService->>DB: getUserPermissions(sessionToken, <br> csrfToken)
    DB-->>AuthService: User Permissions
    AuthService-->>Filter: User Permissions
    alt User does not have <br> access to the repo
        Filter-->>Client: 403 Forbidden <br> (Insufficient Permissions)
    else User has sufficient access
        Filter->>Controller: cloneRepo(owner, name, userDto)
        Controller->>AuthService: getPat(userDto)
        AuthService-->>Controller: decrypted GitHub PAT
    end

    Controller-->>Service: isCloned(owner, name)
    alt Repo already cloned on disk
        Service-->>Controller: true
        Controller->>Service: updateRepo(owner, <br> name, GitHub PAT)
        Service->>Library: fetch(repoUrl, GitHub PAT)
        Controller->>Client: 200 OK
    else Repo not found on disk
        Service-->>Controller: false
        Controller->>Service: updateRepo(owner, <br> name, GitHub PAT)
        Service->>Library: cloneRepository(repoUrl, <br> GitHub PAT)
        Controller->>Client: 201 Created
    end
